### ISSUE TITLE
can't run seeder

### ISSUE THREAD

**Issue by G3z** [sequelize/cli#322] opened 2016-07-11 22:43 UTC
i'm trying to run this simple seeder

``` javascript
'use strict';

module.exports = {
    up(queryInterface) {
        return queryInterface.bulkInsert('Users',
            [{
                username: 'aaaa',
                password: 'qweqwe',
                email: '##',
                profile: {
                    name: 'aaa',
                    surname: 'bbb',
                },
                createdAt: Date.now(),
                updatedAt: Date.now(),
            }, {
                username: 'ccc',
                password: 'qweqwe',
                email: '##',
                profile: {
                    name: 'ddd',
                    surname: 'eee',
                },
                createdAt: Date.now(),
                updatedAt: Date.now(),
            }]
        );
    },

    down(queryInterface) {
        return queryInterface.bulkDelete('Users', null, {});
    },
};

```

``` zsh
⇒ sequelize db:seed:all

Sequelize [Node: 6.3.0, CLI: 2.4.0, ORM: 3.23.3, pg: ^6.0.1]

(node:31807) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loaded configuration file "config/config.json".
Using environment "development".
== 20160711203859-users-seeder: migrating =======
Seed file failed with error: val.replace is not a function
```

i tried to debug but couldn't follow track down the call.
what am i doing wrong ?

also i use this `return queryInterface.bulkInsert('Users', [{}]);` as `up()`

this is the result

``` zsh
⇒ sequelize db:seed:all

Sequelize [Node: 6.3.0, CLI: 2.4.0, ORM: 3.23.3, pg: ^6.0.1]

(node:32089) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loaded configuration file "config/config.json".
Using environment "development".
== 20160711203859-users-seeder: migrating =======
Seed file failed with error: syntax error at or near ")"
```

**Comment by diosney** [comment] 2016-07-27 21:52
Same here.

Sadly enough, using the same code in a migration, works fine.

**Comment by diosney** [comment] 2016-07-27 22:13
@mickhansen @janmeier Any ideas on how to debug it? I can happily dig on this to fix it.

**Comment by diosney** [comment] 2016-07-27 22:44
I dig a little more and found that the error (in my case and probably yours too) is caused by the appearance of a nested object in the `bulkInsert` data, as `profile` is.

The following error is triggered when I remove the catch clause, which doesnt give much info about it:

```
Unhandled rejection TypeError: val.replace is not a function
    at SqlString.escape (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/sql-string.js:63:15)
    at wrapper (/home/diosney/Projects/booking-api/node_modules/sequelize/node_modules/lodash/lodash.js:4663:19)
    at Array.map (native)
    at Object.SqlString.escape (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/sql-string.js:55:16)
    at Object.QueryGenerator.escape (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:977:22)
    at Object.<anonymous> (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:356:23)
    at Array.map (native)
    at Object.<anonymous> (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:352:23)
    at Array.forEach (native)
    at Object.QueryGenerator.bulkInsertQuery (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:350:21)
    at QueryInterface.bulkInsert (/home/diosney/Projects/booking-api/node_modules/sequelize/lib/query-interface.js:568:33)
    at Object.module.exports.up (/home/diosney/Projects/booking-api/seeders/20160727222414-unnamed-seeder.js:30:27)
    at module.exports.redefine.Class._exec (/home/diosney/Projects/booking-api/node_modules/umzug/lib/migration.js:103:23)
    at module.exports.redefine.Class.up (/home/diosney/Projects/booking-api/node_modules/umzug/lib/migration.js:69:17)
    at .<anonymous> (/home/diosney/Projects/booking-api/node_modules/umzug/index.js:124:28)
    at PassThroughHandlerContext.finallyHandler (/home/diosney/Projects/booking-api/node_modules/bluebird/js/release/finally.js:56:23)
```

It seems that at  `sequelize/lib/sql-string.js:63:15` it threw the error due invoking `replace`, a String method, in the passed Object, which doesnt have it.

In my case all is reduced on the following question:

How insert associated data with the `bulkInsert` method in the same query to not have to do two separated queries?

**Comment by docksteaderluke** [comment] 2017-03-10 20:42
I'm running into the same issue. Any progress on this?

**Comment by diosney** [comment] 2017-03-10 21:16
I ended up with separated seeders for the nested data., just in case it solves your issue.

**Comment by docksteaderluke** [comment] 2017-03-15 22:59
I'm not using any nested data, just an array of simple objects. Here's what my `up` function looks like:

```
return queryInterface.bulkInsert('Relationship', [
  { id : Sequelize.UUIDV4(), name : "Aunt" },
  { id : Sequelize.UUIDV4(), name : "Uncle" },
  { id : Sequelize.UUIDV4(), name : "Brother" },
  { id : Sequelize.UUIDV4(), name : "Sister" },
  { id : Sequelize.UUIDV4(), name : "Mother" },
  { id : Sequelize.UUIDV4(), name : "Father" },
  ...
])
```

Any idea why I keep getting this error?

> Seed file failed with error: val.replace is not a function

**Comment by 3bola** [comment] 2017-03-24 15:04
I would love to see an update on this issue, because this also fails when I am trying to seed PostGIS location data.

```js
return queryInterface.bulkInsert('place', [{
  key: 'foo-bar',
  name: 'Foo Bar',
  location: { type: 'Point', longitide: [ 20.123, 60.123] },
}]);
```

**Comment by sushantdhiman** [comment] 2017-09-16 12:11
Closing (Issue Cleanup), Please comment if you want to keep it open

**Closed by sushantdhiman** 2017-09-16 12:11 UTC

**Comment by kaikash** [comment] 2019-03-07 16:30
@3bola have you found solution?

**Comment by AshwinTayson** [comment] 2019-09-17 15:31
This issue still persists. Seeders were working properly. But weirdly it is throwing Unexpected token or identifier. I tried to remove all ES6 code, then it works. If I have ES6 code in migrations, it works without any issues. Please reopen this.

**Comment by papb** [comment] 2019-09-17 16:41
@AshwinTayson 

> I tried to remove all ES6 code, then it works. If I have ES6 code in migrations, it works without any issues.

This is contradictory, please clarify, thanks!

**Comment by dkayzee** [comment] 2019-11-06 17:28
@papb I don't think it's contradictory. I'm having the same issues and I don't know how else to explain it. No issues with ES6 when running migrations but using the same syntax and format for seeders causes problems. When removing ES6 in seeders, it works.

**Comment by papb** [comment] 2019-11-06 19:35
Ah, I think I get it now:

* ES6 code works at migrations
* ES6 code doesn't work at seeders

@dkayzee is this correct?

**Comment by AshwinTayson** [comment] 2020-02-25 09:10
> Ah, I think I get it now:
> 
> * ES6 code works at migrations
> * ES6 code doesn't work at seeders
> 
> @dkayzee is this correct?

Yes that's correct

**Comment by dkayzee** [comment] 2020-02-25 20:52
@papb yes that is correct! sorry i didn't get back to this. Thanks @AshwinTayson

**Comment by danoseun** [comment] 2020-04-18 21:43
To solve this, npm install --save-dev @babel/register then in your .sequelizerc file put this on top
`require("babel-register");`
