### ISSUE TITLE
is there any way to run sequelize-cli with npm exec

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/cli#1312] opened 2023-06-02 22:33 UTC
when I use 
`npx sequelize-cli migration:generate --name create_user_table`
it works and I know I can use npm exec as well
`
 npm exec --package=sequelize-cli --  migration:generate --name create_user_table11`
but I would lilke to directly call sequelize-cli as in the node image I use I have no access to npm or npx
is there any way to run sequelize-cli with directly without using npm or npx?

**Comment by WikiRik** [comment] 2023-06-05 20:23
Closing this as it's a duplicate of #1302

**Closed by WikiRik** 2023-06-05 20:23 UTC
Labels: type: bug
