### ISSUE TITLE
Promise warnings (still got 'em)

### ISSUE THREAD

**Issue by tedbreen** [sequelize/cli#247] opened 2016-01-08 19:57 UTC
I am still getting the promise warning in **sequelize 3.17.1** when i run a migration (`sequelize db:migrate`)

#### terminal output:
```sh
Sequelize [Node: 4.2.3, CLI: 2.2.1, ORM: 3.17.1, pg: ^4.4.3]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile ~/movie-awards/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
Finished 'db:migrate' after 54 ms
Warning: a promise was created in a handler but was not returned from it
    at ConnectionManager.getConnection (/Users/tedbreen/movie-awards/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:23)
    at Sequelize.query (/Users/tedbreen/movie-awards/node_modules/sequelize/lib/sequelize.js:795:83)
    at QueryInterface.showAllTables (/Users/tedbreen/movie-awards/node_modules/sequelize/lib/query-interface.js:304:25)
    at ensureCurrentMetaSchema (/Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/tasks/db.js:205:6)
    at /Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/tasks/db.js:24:9
    at /Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/tasks/db.js:321:7
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.then (/Users/tedbreen/movie-awards/node_modules/sequelize/lib/promise.js:21:17)
    at getMigrator (/Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/tasks/db.js:320:6)
    at Object.module.exports.db:migrate.task (/Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/Users/tedbreen/movie-awards/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/Users/tedbreen/movie-awards/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/tedbreen/movie-awards/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/tedbreen/movie-awards/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/tedbreen/movie-awards/node_modules/orchestrator/index.js:134:8)
    at /Users/tedbreen/movie-awards/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
== 20160107135123-foobar: migrating =======
CREATE TABLE: movies
CREATE TABLE: awards
== 20160107135123-foobar: migrated (0.023s)
```

#### config/config.json file:
```json
{
  "development": {
    "url": "postgres://tedbreen@localhost/movie_awards",
    "dialect": "postgres",
    "migrationStorage": "json",
    "migrationStoragePath": "sequelize-meta.json"
  }
}
```

**Comment by Americas** [comment] 2016-01-12 10:39
This seems to be telling you that you are creating promises that are missing a `return` statement. But I can't really be sure without knowing the code you are running.

**Comment by tedbreen** [comment] 2016-01-12 16:21
Here's one example without any `return` statements:
```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    queryInterface.createTable('movies', {
      id: {
        type: Sequelize.INTEGER
      , primaryKey: true
      , autoIncrement: true
      }
    , title: {
        type: Sequelize.STRING
      , defaultValue: false
      , allowNull: false
      }
    })
  },

  down: function (queryInterface, Sequelize) {
    queryInterface.dropTable('movies')
  }
};
```

Here's the same example, plus `return` statements:
```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('movies', {
      id: {
        type: Sequelize.INTEGER
      , primaryKey: true
      , autoIncrement: true
      }
    , title: {
        type: Sequelize.STRING
      , defaultValue: false
      , allowNull: false
      }
    })
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('movies')
  }
};
```

Here's the same example, plus `return` statements and `then()` methods:
```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('movies', {
      id: {
        type: Sequelize.INTEGER
      , primaryKey: true
      , autoIncrement: true
      }
    , title: {
        type: Sequelize.STRING
      , defaultValue: false
      , allowNull: false
      }
    }).then(function () {
      return
    })
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('movies').then(function () {
      return
    })
  }
}
```

Same result everytime. These migrations work. I just get those promise errors.

**Comment by Americas** [comment] 2016-01-12 16:48
I cannot reproduce the promise errors.

**Comment by tedbreen** [comment] 2016-01-12 18:22
@Americas Thanks for trying.

**Comment by Americas** [comment] 2016-01-13 09:43
@tedbreen after some tinkering, I found that bluebird does emit that warning, but some configurations need to be turned on.

I found these two environment variables (BLUEBIRD_WARNINGS and BLUEBIRD_LONG_STACK_TRACES) that if you set them to a true value, they will spit out that warning. This is also activated if you explicitly set NODE_ENV to `development`, which I guess is your case.

The underlying warning is being generated in sequelize, and not sequelize-cli, so I would suggest that you take this issue there. I have tried fixing the code that is causing this, but as of yet, I have only met with frustration :disappointed:

If you don't want to see the warnings, you could just not pass the NODE_ENV variable to sequelize-cli, since it defaults to `development` anyways. Optionally, you could pass the `--env=development` option.

**Comment by Americas** [comment] 2016-01-22 10:19
@sdepold this warning is unrelated to that merge. I already mentioned that this happens on sequelize.

I can confirm that #251 does not remove this warning :wink:

**Comment by sdepold** [comment] 2016-01-22 10:28
Oh it was closed by github automatically

**Comment by ronenteva** [comment] 2016-02-11 12:05
+1

**Comment by emadow** [comment] 2016-03-02 17:47
+1

We're on the latest versions of sequelize (`3.19.3`) and sequelize-cli (`2.3.1`). We've also ensured our migrations correctly return promises.

**Comment by opatut** [comment] 2016-03-21 11:09
> The underlying warning is being generated in sequelize, and not sequelize-cli, so I would suggest that you take this issue there.

Actually, I think the warning comes from here: https://github.com/sequelize/cli/blob/master/lib/tasks/db.js#L368

I guess it would help to rewrite `getMigrator` to return a promise instead of running a callback. With `gulp-promise` it might then even be possible to get rid of the output below and acutally wait for the task to finish.

> Finished 'db:migrate' after 99 ms

**Comment by DeX3** [comment] 2016-03-24 16:02
+1

Receiving the exact same issue with sequelize `3.19.3` and `2.3.1`.

**Comment by meddy** [comment] 2016-03-31 14:27
+1

**Comment by leebenson** [comment] 2016-04-24 18:37
+1

**Closed** 2016-04-25 04:28 UTC
