### ISSUE TITLE
Unhandled rejection error on running sequelize db:migrate

### ISSUE THREAD

**Issue by ysholqamy** [sequelize/cli#129] opened 2015-04-28 22:52 UTC
When I try to run any migration this error is thrown. I checked mysql and everything is fine. 
```
Loaded configuration file 'config/config.json'.
Using environment 'development'.
== 20150429014610-create-user: migrating =======
Unhandled rejection Error: [object Object],[object Object]
    at Object.ensureErrorObject (/Users/devj/development/node/testo/node_modules/sequelize/node_modules/bluebird/js/main/util.js:228:20)
    at Promise._rejectUncheckedCheckError (/Users/devj/development/node/testo/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:606:22)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
And here is the migration
```
"use strict";
module.exports = {
  up: function(migration, DataTypes, done) {
    migration.createTable("Users", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: DataTypes.INTEGER
      },
      name: {
        type: DataTypes.STRING
      },
      createdAt: {
        allowNull: false,
        type: DataTypes.DATE
      },
      updatedAt: {
        allowNull: false,
        type: DataTypes.DATE
      }
    }).done(done);
  },
  down: function(migration, DataTypes, done) {
    migration.dropTable("Users").done(done);
  }
};
```

**Comment by usfhussam** [comment] 2015-04-28 23:28
looks like the sequelize@2.1.0 is supported by sequelize-cli@1.7.0. Was running on sequelize@2.1.0 and sequelize-cli@1.4.0 which generated seemingly different migrations from the newer version. reverting to older version solved the problem.

**Comment by sdepold** [comment] 2015-04-29 04:12
Hi. You are right. A recent change in the cli generates different migrations. But: the old migrations should still work. Just to make that sure: if you take the above migration and run it with cli 1.4.0 it crashes?

**Comment by usfhussam** [comment] 2015-04-29 11:39
The cli version is 1.4.0 and it crashes. 
```
Sequelize [Node: 0.12.0, CLI: 1.4.0, ORM: 2.1.0]

Loaded configuration file 'config/config.json'.
Using environment 'development'.
== 20150429143112-create-user: migrating =======
Unhandled rejection Error: [object Object],[object Object]
    at Object.ensureErrorObject (/Users/devj/development/node/testo/node_modules/sequelize/node_modules/bluebird/js/main/util.js:228:20)
    at Promise._rejectUncheckedCheckError (/Users/devj/development/node/testo/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:606:22)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

but on changing the orm version to 2.0.4 instead of 2.1.0 the migration runs smoothly
```
Sequelize [Node: 0.12.0, CLI: 1.4.0, ORM: 2.0.4]

Loaded configuration file 'config/config.json'.
Using environment 'development'.
== 20150429143112-create-user: migrating =======
== 20150429143112-create-user: migrated (0.040s)
```

So the problem is apparently the combination of sequelize@2.1.0 and sequelize-cli@1.4.0. Should either use sequelize@2.0.4 and sequelize-cli@1.4.0 or updated both to latest i think.

**Comment by Americas** [comment] 2015-04-29 14:16
version 2.1.0 of sequelize removed the done callback, and now migrations should just return promises.

```js
"use strict";
module.exports = {
  up: function(migration, DataTypes) {
    return migration.createTable("Users", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: DataTypes.INTEGER
      },
      name: {
        type: DataTypes.STRING
      },
      createdAt: {
        allowNull: false,
        type: DataTypes.DATE
      },
      updatedAt: {
        allowNull: false,
        type: DataTypes.DATE
      }
    });
  },
  down: function(migration, DataTypes) {
    return migration.dropTable("Users");
  }
};
```
This works for me.

**Comment by mickhansen** [comment] 2015-04-29 14:20
Corret, sequelize 2.1.0 removed events support. Newer versions of the CLI use umzug which should handle this case i believe.

**Comment by usfhussam** [comment] 2015-04-29 15:26
Removing done callback solved the problem, which is basically changing the migration to the newer format. Point is sequelize-cli@1.4.0 will keep generating older version of migrations when used alongside sequelize@2.1.0 which will cause migrations to break. Thanks a lot!

**Comment by sdepold** [comment] 2015-08-28 04:58
I'm closing this ticket as the CLI generates proper migrations already.

**Closed by sdepold** 2015-08-28 04:58 UTC
