### ISSUE TITLE
Support for Native Typescript for migrations and seeders

### ISSUE THREAD

**Issue by larongbingo** [sequelize/cli#771] opened 2019-04-15 13:22 UTC
Since Sequlize v5 has been released with its own typings, any plans on bringing typescript support for the cli?

This has been raised at this(#693) issue, but no one took notice.

**Comment by fdorantesm** [comment] 2019-05-09 15:18
Do you know about babel and ES6? 🤨

**Comment by papb** [comment] 2019-10-30 11:34
Duplicate of #693

**Closed by papb** 2019-10-30 11:34 UTC
