### ISSUE TITLE
Sequelize CLI appears to silently fail when PG < 8

### ISSUE THREAD

**Issue by starbugs** [sequelize/cli#889] opened 2020-05-02 22:41 UTC
sequelize-cli appears to be silently failing (not doing anything) when PG version is below 8.

Output with "pg": "^7.12.1":

```
Sequelize CLI [Node: 14.1.0, CLI: 5.5.1, ORM: 5.21.7]

Loaded configuration file "packages/backend/config/config.json".
Using environment "development".
(node:49105) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Output with "pg": "^8.0.3":

```
Sequelize CLI [Node: 14.1.0, CLI: 5.5.1, ORM: 5.21.7]

Loaded configuration file "packages/backend/config/config.json".
Using environment "development".
(node:49105) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
(Use `node --trace-deprecation ...` to show where the warning was created)
Database testdb created.
```

**Comment by thecpdubguy** [comment] 2020-05-20 18:28
Closing my issue #896 as it appears to be identical to here. Expanding upon this -> sequelize.authenticate() hung indefinitely - may be related.

**Comment by sushantdhiman** [comment] 2020-06-22 05:53
Duplicate of https://github.com/sequelize/sequelize/issues/12158

**Closed by sushantdhiman** 2020-06-22 05:53 UTC
