### ISSUE TITLE
Promise warnings

### ISSUE THREAD

**Issue by joshuakarjala** [sequelize/cli#242] opened 2015-12-22 15:51 UTC
When running `sequelize db:migrate` I get warning like the ones referenced in https://github.com/sequelize/sequelize/issues/4883

Is there some code you need to fix in `sequeliaze-cli` as well?

```
Sequelize [Node: 4.2.1, CLI: 2.2.1, ORM: 3.15.0]

Loaded configuration file "modules/db/config/config.json".
Using environment "development".
Using gulpfile /src/node_modules/sequelize-cli/lib/gulpfile.js
Warning: a promise was created in a handler but was not returned from it
    at ConnectionManager.getConnection (/src/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:237:23)
    at Sequelize.query (/src/node_modules/sequelize/lib/sequelize.js:794:83)
    at QueryInterface.showAllTables (/src/node_modules/sequelize/lib/query-interface.js:301:25)
    at ensureCurrentMetaSchema (/src/node_modules/sequelize-cli/lib/tasks/db.js:205:6)
    at /src/node_modules/sequelize-cli/lib/tasks/db.js:24:9
    at /src/node_modules/sequelize-cli/lib/tasks/db.js:321:7
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Promise.then (/src/node_modules/sequelize/lib/promise.js:21:17)
    at getMigrator (/src/node_modules/sequelize-cli/lib/tasks/db.js:320:6)
    at Object.module.exports.db:migrate.task (/src/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/src/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /src/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
No migrations were executed, database schema was already up to date.
```

**Comment by sdepold** [comment] 2015-12-23 12:22
Yeah it's directly related to sequelize and will be fixed once it's resolved in sequelize.

Apparently the issue is here

```
    at ConnectionManager.getConnection (/src/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:237:23)
```

**Comment by AlexNasonov** [comment] 2015-12-24 12:45
The same I get on `model.findById(id)` using postgres

**Comment by mychaelgo** [comment] 2015-12-26 13:38
+1

**Comment by tedbreen** [comment] 2016-01-07 23:01
+1

**Comment by sdepold** [comment] 2016-01-08 06:01
Updating sequelize should apparently fix the problem. Please open a new ticket if it's still an issue

**Closed by sdepold** 2016-01-08 06:01 UTC

**Comment by mstmustisnt** [comment] 2016-02-04 09:13
+1
facing the same issue with the newest sequelize(3.19.1), but everyhing is ok with v3.13.0

**Comment by Americas** [comment] 2016-02-05 11:15
as I mentioned in issue #247 this is a sequelize problem, related to using NODE_ENV=development that tells bluebird to show that warning.
